services:

  redis:
    image: redis:7
    container_name: contenedor-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    restart: unless-stopped

  servicio-cache:
    build: ./cache
    container_name: contenedor-cache
    depends_on:
      kafka:
        condition: service_started
      redis:
        condition: service_started
    environment:
      KAFKA_BROKER: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      URL_METRICAS: http://metricas:5002/registrar
    ports:
      - "5000:5000"
    restart: unless-stopped

  generador-trafico:
    build: ./generador-trafico
    container_name: contenedor-trafico
    depends_on:
      kafka:
        condition: service_started
    environment:
      KAFKA_BROKER: kafka:9092
    restart: "no"

  generador-respuestas:
    build: ./generador-respuestas
    container_name: contenedor-respuestas
    depends_on:
      kafka:
        condition: service_started
    environment:
      KAFKA_BROKER: kafka:9092
    restart: unless-stopped

  metricas:
    build: ./Metricas
    container_name: contenedor-metricas
    depends_on:
      kafka:
        condition: service_started
      redis:
        condition: service_started
    environment:
      KAFKA_BROKER: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - "5002:5002"
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    restart: unless-stopped

  spark:
    build: ./procesamiento-streaming
    container_name: contenedor-spark
    depends_on:
      - kafka
      - elasticsearch

    environment:
      KAFKA_BROKER: kafka:9092

    command: >
      spark-submit
      --master local[*]
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.elasticsearch:elasticsearch-spark-30_2.12:8.11.0
      /app/job_spark.py

    ports:
      - "4040:4040"
    restart: unless-stopped